spring:
  application:
    name: client-authcode

  redis:
    host: r-2ze3vf7vdvw0ics2j9pd.redis.rds.aliyuncs.com
    port: 6379
    password: Redispassword123
    database: 2
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 100ms
server:
  port: 6102
  servlet:
    context-path: /client-authcode

#  Oauth2提供的默认端点（endpoints）
#  /oauth/authorize：授权端点
#  /oauth/token：令牌端点
#  /oauth/confirm_access：用户确认授权提交端点
#  /oauth/error：授权服务错误信息端点
#  /oauth/check_token：用于资源服务访问的令牌解析端点
#  /oauth/token_key：提供公有密匙的端点，如果使用JWT令牌的话

security:
  oauth2:
    client:
      client-id: code-client
      client-secret: code-secret-8888
      user-authorization-uri: http://localhost:6001/oauth/authorize
      access-token-uri: http://localhost:6001/oauth/token
    resource:
      jwt:
        key-uri: http://localhost:6001/oauth/token_key
        key-value: dev
    authorization:
      check-token-access: http://localhost:6001/oauth/check_token

