spring:
  application:
    name: auth-server

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://yjhtest1.mysql.polardb.rds.aliyuncs.com/test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: yjhuser
    password: Yjh123Password
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 9

  redis:
    host: r-2ze3vf7vdvw0ics2j9pd.redis.rds.aliyuncs.com
    port: 6379
    password: Redispassword123
    database: 2
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 100ms

server:
  port: 6001


management:
  endpoint:
    health:
      enabled: true




